name: fixi_mobile
description: Fixi mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  dio: ^5.7.0
  intl: ^0.20.2
  path_provider: ^2.1.4
  shared_preferences: ^2.5.5
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  color_dark: "#FFFFFF"
  image_dark: assets/icon.png
  android: true
  ios: false
  web: false
  fullscreen: true

dependency_overrides:
  objective_c: 9.1.0
